{
  "hash": "f627c9f6cd8490f9dca978cf0f093a2d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"POCKET MONEY(A3)\"\nauthor: \"harvallav\"\n---\n\n\n\n# The Great Money Showdown\n\n## Introduction\n\nIn a world where digital wallets reign supreme, the age-old debate of who holds the purse strings—guys or gals—still ignites curiosity. So, let’s dive into the numbers and see if the guys really do have more money than the gals!\n\n![](money.jpg) \n\n### Setting up the packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(readr)\n```\n:::\n\n\n\n### Reading the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoney <-read_csv(\"../../data /money.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\nRows: 82 Columns: 5\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(2): Name, Gender dbl (2): Sr no, Money_spent lgl (1): ...5\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...5`\n```\n\n\n:::\n\n```{.r .cell-code}\nmoney\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 82 × 5\n   `Sr no` Name     Gender Money_spent ...5 \n     <dbl> <chr>    <chr>        <dbl> <lgl>\n 1       1 Aagam    Male           150 NA   \n 2       2 Aakash   Male           240 NA   \n 3       3 Aarushi  Female         382 NA   \n 4       4 Abheeta  Female          60 NA   \n 5       5 Adithya  Male            68 NA   \n 6       6 Aditya   Male           300 NA   \n 7       7 Akanksha Female         270 NA   \n 8       8 Amruta   Female         190 NA   \n 9       9 Anaaya   Female         300 NA   \n10      10 Anish    Male             0 NA   \n# ℹ 72 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(money)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 82\nColumns: 5\n$ `Sr no`     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…\n$ Name        <chr> \"Aagam\", \"Aakash\", \"Aarushi\", \"Abheeta\", \"Adithya\", \"Adity…\n$ Gender      <chr> \"Male\", \"Male\", \"Female\", \"Female\", \"Male\", \"Male\", \"Femal…\n$ Money_spent <dbl> 150, 240, 382, 60, 68, 300, 270, 190, 300, 0, 250, 85, 700…\n$ ...5        <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\n## Data Dictionary \n\n| Column Name     | Type | Description                                                                                     |\n|-----------------|------|-------------------------------------------------------------------------------------------------|\n| Sr no           | Quan | Serial number uniquely identifying each entry in the dataset.                                   |\n| Name            | Qual | Name of the participant                                              |\n| Gender          | Qual | Gender of the participant                                              |\n| Money_spent     | Quan | Amount of money spent by the participant, represented as a numeric value . |\n| ...5            | NA   | An empty column with no data :/  |\n\n\n\n## Let's Make a Histogram for this dataset first\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ Money_spent | ~ Gender, data = money) %>%\n  gf_labs(title = \"MONEY SPENT v/s GENDER\", caption = \"ggformula\")\n```\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n## Making a CROSS TABLE\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoney%>% \n  crosstable(Money_spent ~ Gender) %>% \n  as_flextable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-51c2c434{table-layout:auto;}.cl-51bf70ea{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-51bf70f4{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-51c0a9ec{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-51c0a9f6{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-51c0b8c4{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-51c0b8c5{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-51c0b8ce{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-51c0b8cf{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-51c0b8d0{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-51c2c434'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-51c0b8c4\"><p class=\"cl-51c0a9ec\"><span class=\"cl-51bf70ea\">label</span></p></th><th  rowspan=\"2\"class=\"cl-51c0b8c4\"><p class=\"cl-51c0a9ec\"><span class=\"cl-51bf70ea\">variable</span></p></th><th  colspan=\"2\"class=\"cl-51c0b8c5\"><p class=\"cl-51c0a9ec\"><span class=\"cl-51bf70ea\">Gender</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-51c0b8ce\"><p class=\"cl-51c0a9ec\"><span class=\"cl-51bf70ea\">Female</span></p></th><th class=\"cl-51c0b8ce\"><p class=\"cl-51c0a9ec\"><span class=\"cl-51bf70ea\">Male</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-51c0b8cf\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">Money_spent</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">Min / Max</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">0 / 1.3e+04</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">0 / 1.0e+04</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">Med [IQR]</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">280.0 [85.0;500.0]</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">250.0 [150.0;842.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">Mean (std)</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">693.3 (2035.8)</span></p></td><td class=\"cl-51c0b8d0\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">748.6 (1636.5)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-51c0b8cf\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">N (NA)</span></p></td><td class=\"cl-51c0b8cf\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">41 (0)</span></p></td><td class=\"cl-51c0b8cf\"><p class=\"cl-51c0a9f6\"><span class=\"cl-51bf70f4\">41 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n### What is Happening Here?\n\nThe data presents a cross table summarizing spending patterns among two groups: females and males. The table outlines the minimum, maximum, median, interquartile range (IQR), mean, and standard deviation of the money spent by each gender.\n\n### Inferences from This Data\n\n1)**Min / Max**: The minimum and maximum amounts spent are summarized as follows: Females: Minimum of 0 and a maximum of 13,000. Males: Minimum of 0 and a maximum of 10,000. This indicates that while both groups have spent nothing (0), females have a wider range of maximum spending compared to males.\n\n3)**Med \\[IQR\\]**: The median spending and IQR for each gender are as follows: Females: Median spending of 280.0 with an IQR ranging from 85.0 to 500.0. Males: Median spending of 250.0 with an IQR ranging from 150.0 to 842.0. Both groups have similar medians, with females spending slightly more. The IQR suggests that the middle 50% of female spenders have a smaller range than that of males.\n\n4)**Mean (std)**: The average spending and its variability are: Females: Mean spending of 693.3 with a standard deviation of 2,035.8. Males: Mean spending of 748.6 with a standard deviation of 1,636.5.\n\n**The average spending for males is slightly higher than for females. The higher standard deviation for females indicates more variability in spending, meaning that while the average is lower, there may be some individuals who spend significantly more, skewing the mean.**\n\n## Let's do the T-test\n\n(to understand this test refer to the tips(a3) blog)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::t.test(Money_spent ~ Gender, data = money) %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1    -55.3      693.      749.    -0.136   0.893      76.5    -868.      757.\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\n\nthe results suggest that there is no statistically significant difference in the amount of money spent between the two groups (females and males). The high p-value and the confidence interval that includes zero imply that any observed difference in spending is likely due to chance rather than a real effect.\n\n# Let us try a few more Graphs\n\n## The Density Plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoney %>%\n  gf_density(\n    ~ Money_spent,\n    fill = ~ Gender,  \n    alpha = 0.5,\n    title = \"Money Spent Densities\",\n    subtitle = \"Females vs Males\"\n  )\n```\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmoney %>%   \n  gf_boxplot( Money_spent ~ Gender,     \n              fill = ~ Gender,     \n              alpha = 0.5,     \n              title = \"Expnses vs Gender\",     \n              subtitle = \"Male vs Female\" )  \n```\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\nThis yields a clearer visual of Money_spent distributions by gender, along with normal distribution fits for comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoney %>% \n  gf_density( ~ Money_spent ,\n            fill = ~ Gender,\n            alpha = 0.5,\n            title = \"Tips across Veg and Non-Veg\") %>% \n  gf_facet_grid(~Gender) %>% \n  gf_fitdistr(dist = \"dnorm\")\n```\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfemale_expenses <- money %>%    \n  filter( Gender == \"Female\") %>%    \n  select(Money_spent) \n##  \nmale_expenses <- money %>%   \n  filter( Gender == \"Male\") %>% \n  select(Money_spent)\n\nmoney %>%    \n  gf_density( ~ log10(Money_spent),             \n              fill = ~ Gender,             \n              alpha = 0.5,             \n              title = \"Expenses across Male and Female\") %>%    \n  gf_facet_grid(~Gender) %>%    \n  gf_fitdistr(dist = \"dnorm\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 6 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 6 rows containing non-finite outside the scale range\n(`stat_fitdistr()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n### What does this tell us ?\n\nTogether with the box plot, these graphs make it clear that the data doesn’t follow a perfect normal distribution. The density plot and QQ plot reveal the actual spread and shape of the data, confirming the insights from the box plot about how the data is distributed.\n\n\n\n## Let's do a Shapiro-Wilk test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(female_expenses$Money_spent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  female_expenses$Money_spent\nW = 0.29606, p-value = 8.961e-13\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(male_expenses$Money_spent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  male_expenses$Money_spent\nW = 0.40726, p-value = 1.136e-11\n```\n\n\n:::\n:::\n\n\n### what does this tell us ?\n\n1)**W value**: The test statistic (W) is far from 1 in both cases (0.29606 for females and 0.40726 for males). In a perfectly normal distribution, W would be closer to 1.\n2) **P-value**: Both p-values (8.961e-13 for females and 1.136e-11 for males) are extremely low, much lower than the typical significance level (like 0.05). This low p-value means we reject the null hypothesis of normality.\nWhat this suggests:\nThese results strongly suggest that the spending data (Money_spent) for both males and females is not normally distributed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(rank(Money_spent) ~ Gender, \n   data = money) %>% \n  broom::tidy(conf.int = TRUE,\n              conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)    39.2       3.72    10.5   9.30e-17    31.8       46.6\n2 GenderMale      4.63      5.27     0.880 3.81e- 1    -5.84      15.1\n```\n\n\n:::\n:::\n\n\n\nwe conclude that gender does not have a statistically significant impact on the amount spent—the observed difference is likely due to random chance.\n\n\n\n## lets do a Wilcox test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(Money_spent~Gender, data = money,\n            conf.int = TRUE,\n            conf.level = 0.95) %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact confidence intervals with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value conf.low conf.high method               alternative\n     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <chr>                <chr>      \n1    -55.0      746.   0.381    -180.      70.0 Wilcoxon rank sum t… two.sided  \n```\n\n\n:::\n:::\n\n\n\n\n## Let's do the Permutation Test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_money <- \n  do(4999) * diffmean(data = money, \n                      Money_spent ~ shuffle(Gender))\n#null_dist_money\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_mean <- money %>%\n  group_by(Gender) %>%\n  summarise(mean_money = mean(Money_spent)) %>%\n  summarise(obs_mean = diff(mean_money)) %>%\npull(obs_mean)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprop1(~ diffmean <= obs_mean, data = null_dist_money)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprop_TRUE \n   0.5572 \n```\n\n\n:::\n:::\n\n\n\nA prop_TRUE value of 0.566 suggests that 56.6% of the permuted mean differences are less than or equal to the observed difference (obs_mean). This indicates that the observed difference is quite common under the null hypothesis, providing little evidence against it.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(data = null_dist_money, ~ diffmean, \n             bins = 25) %>%\n  gf_vline(xintercept = obs_mean, \n           colour = \"blue\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Histogram\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_money%>%  \n  gf_ecdf( ~ diffmean,          \n           linewidth = 1) %>%   \n  gf_vline(xintercept = obs_mean,             \n           colour = \"blue\", linewidth = 1,            \n           title = \"Null Distribution by Permutation\",             \n           subtitle = \"Cumulative Density\") %>%    \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index3_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n## Result \n\nThis result suggests that the observed difference in spending between males and females is not statistically significant. Since the observed mean difference falls well within the range of differences generated by random permutations, it implies that this difference could likely occur by chance alone. Consequently, there is insufficient evidence to claim a real or meaningful difference in spending between the genders in this dataset.\n\n\n\n",
    "supporting": [
      "index3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}