{
  "hash": "44c28078d058142c26bf2e9d2fcf450f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"TIPS(A3)\"\nauthor: \"harvallav\"\n---\n\n\n\n# TIP TADKA\n\n## A Flavorful Comparison Between Veg and Non-Veg Diners\n\n### Introduction\n\nIn this data set we are exploring if vegetarians the real kanjoos, or do the meat-eaters hold the crown? To settle it, we’ll dive into those Swiggy, Zomato, and Dining Out bills and pull out the ultimate truth .\n\n![](veg.jpg)\n\n### Setting up the packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(readr)\n```\n:::\n\n\n\n### Reading the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip <-read_csv(\"../../data /tip.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 60 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): Name, Gender, Preferance\ndbl (1): Tip\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ntip \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 60 × 4\n   Name     Gender Preferance   Tip\n   <chr>    <chr>  <chr>      <dbl>\n 1 Aanya    Female Veg            0\n 2 Adit     Male   Veg            0\n 3 Aditi    Female Veg           20\n 4 Akash    Male   Non-veg        0\n 5 Akshita  Female Non-veg        0\n 6 Anandita Female Non-veg        0\n 7 Ananya   Female Non-veg       20\n 8 Anaya    Female Veg           35\n 9 Anhuya   Female Veg           40\n10 Ankit    Male   Non-veg        0\n# ℹ 50 more rows\n```\n\n\n:::\n:::\n\n\n\nThis data provides information on individuals' names, genders, dietary preferences (veg or non-veg), and the tips they’ve given.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(tip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60\nColumns: 4\n$ Name       <chr> \"Aanya\", \"Adit\", \"Aditi\", \"Akash\", \"Akshita\", \"Anandita\", \"…\n$ Gender     <chr> \"Female\", \"Male\", \"Female\", \"Male\", \"Female\", \"Female\", \"Fe…\n$ Preferance <chr> \"Veg\", \"Veg\", \"Veg\", \"Non-veg\", \"Non-veg\", \"Non-veg\", \"Non-…\n$ Tip        <dbl> 0, 0, 20, 0, 0, 0, 20, 35, 40, 0, 0, 0, 0, 0, 0, 0, 20, 0, …\n```\n\n\n:::\n:::\n\n\n\n## Data dictionary\n\n| Column Name | Type | Description |\n|-----------|-----------|--------------------------------------------------|\n| Name | Qual | Name of the participant. |\n| Gender | Qual | Gender of the participant. |\n| Preferance | Qual | Dietary preference of the participant, such as vegetarian or non-vegetarian. |\n| Tip | Quan | Tip amount given by the participant, represented as a numeric value. |\n\n\n\n## Let's Make a Histogram for this dataset first\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ Tip| ~ Preferance, data = tip)%>%\n  gf_labs(title = \"TIP v/s PREFERANCE\", caption=\"ggformula\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nBy splitting the histogram by dietary preference, it allows for a comparative analysis of how tips vary within each group, making it easier to see distributions, frequencies, and any notable trends in tipping behavior.\\\nHowever, histograms primarily show the frequency of observations within specific ranges and do not provide a direct comparison of averages between groups.\n\nLet us try making a cross table.\n\n## Making a CROSS TABLE\n\nThis is a cross table, often used to summarize and compare key statistics for different groups within a dataset, such as minimum and maximum values, median with interquartile range (IQR), mean with standard deviation (std), and count (N) along with missing values (NA) for each category.\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip %>% crosstable(Tip~Preferance ) %>% as_flextable\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-5ac157b2{table-layout:auto;}.cl-5abe44d2{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-5abe44dc{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-5abf9378{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-5abf9379{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-5abfa110{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5abfa111{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5abfa11a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5abfa11b{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-5abfa11c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-5ac157b2'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-5abfa110\"><p class=\"cl-5abf9378\"><span class=\"cl-5abe44d2\">label</span></p></th><th  rowspan=\"2\"class=\"cl-5abfa110\"><p class=\"cl-5abf9378\"><span class=\"cl-5abe44d2\">variable</span></p></th><th  colspan=\"2\"class=\"cl-5abfa111\"><p class=\"cl-5abf9378\"><span class=\"cl-5abe44d2\">Preferance</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-5abfa11a\"><p class=\"cl-5abf9378\"><span class=\"cl-5abe44d2\">Non-veg</span></p></th><th class=\"cl-5abfa11a\"><p class=\"cl-5abf9378\"><span class=\"cl-5abe44d2\">Veg</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-5abfa11b\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">Tip</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">Min / Max</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">0 / 50.0</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">0 / 100.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">Med [IQR]</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">0 [0;20.0]</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">0 [0;20.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">Mean (std)</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">10.0 (12.9)</span></p></td><td class=\"cl-5abfa11c\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">12.3 (21.9)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-5abfa11b\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">N (NA)</span></p></td><td class=\"cl-5abfa11b\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">30 (0)</span></p></td><td class=\"cl-5abfa11b\"><p class=\"cl-5abf9379\"><span class=\"cl-5abe44dc\">30 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n### What is Happening Here?\n\nThe data presents a cross table summarizing tipping patterns among two groups: vegetarians and non-vegetarians.\n\n### Inferences from This Data\n\n1)**Min / Max**: Shows the minimum and maximum tip values for non-vegetarians (0 and 50) and vegetarians (0 and 100).\n\n2)**Med \\[IQR\\]**: Shows the median tip and IQR for each group. Both groups have a median tip of 0, with an IQR ranging from 0 to 20.\n\n3)**Mean (std)**: Shows the average tip and its variability. Non-vegetarians have a mean tip of 10.0 with a standard deviation of 12.9, while vegetarians have a slightly higher mean of 12.3 with a standard deviation of 21.9, indicating more variability in the vegetarian group.\n\nNOW, from what I understand so far,\\\nAlthough the average tip for non-vegetarians (10.0) is lower than that for vegetarians (12.3), this does not establish that non-vegetarians tip more. Instead, it suggests the opposite. To prove non-vegetarians tip more, you would expect their average to be higher.\\\nThe standard deviation indicates that the vegetarian group has more variability in tipping. This variability means that while their average is higher, there may be some individuals giving very high tips that affect the mean.\\\n\nThe cross table gives a helpful summary of the data, but to make strong conclusions about how dietary preferences affect tipping, we need to do more detailed statistical analysis.\n\n## Let's do the T-test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::t.test(Tip~ Preferance,data=tip) %>% \n                 broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1    -2.33        10      12.3    -0.503   0.617      46.9    -11.7      6.99\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\n\nThe t-test checks whether there is a statistically significant difference in the average tips given by vegetarians and non-vegetarians.\n\n### What is happening here ?\n\nA **chai test**, just kidding.\n\nThink of a t-test like brewing chai. When you make chai, you combine ingredients like tea leaves, milk, sugar, and spices. The resulting flavor depends on the balance of these ingredients.\n\nIn the same way, a t-test combines data from two groups (like vegetarians and non-vegetarians) to see if their average tips differ significantly. Just as you assess the taste of chai by comparing it to plain tea, the t-test assesses whether the differences in averages are strong enough to be meaningful, rather than just a result of random variations.\n\nSo, just as a good chai highlights the right balance of flavors, a t-test helps identify whether the differences between groups are noteworthy or simply due to chance.\n\n### Inferences from This Data\n\n1)**Means**:Vegetarians: Average tip of 10. Non-vegetarians: Average tip of approximately 12.33. 2) **T-Statistic**:The t-statistic is approximately -0.50, indicating that the observed difference in means is relatively small compared to the variability within the groups.\\\n3) **P-Value**:The p-value is 0.617, which is significantly higher than the common alpha level of 0.05. This suggests that the difference in average tips between vegetarians and non-vegetarians is not statistically significant.\\\n4) **Confidence Interval**:The 95% confidence interval for the difference in means ranges from approximately -11.66 to 6.99. This interval includes zero, further indicating that there is no statistically significant difference between the two groups.\n\n*The results suggest that there is no strong evidence to support the claim that non-vegetarians give higher average tips than vegetarians. The lack of statistical significance (high p-value and confidence interval including zero) indicates that any observed differences in average tips could be due to random chance rather than a true effect related to dietary preference. Thus, dietary preference does not appear to have a meaningful impact on tipping behavior based on this dataset.*\n\n# Let us try a few more tests\n\n## The Density Plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip %>%\n  gf_density(\n    ~ Tip,\n    fill = ~ Preferance,  \n    alpha = 0.5,\n    title = \"Tip Amount Densities\",\n    subtitle = \"Vegetarians vs Non-Vegetarians\"\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntip %>%\n  gf_boxplot(\n    Tip ~ Preferance,\n    fill = ~ Preferance,\n    alpha = 0.5,\n    title = \"Tips Score Box Plots\",\n    subtitle = \"Veg vs Non-Veg\"\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntip %>% \n  gf_density( ~ Tip,\n            fill = ~ Preferance,\n            alpha = 0.5,\n            title = \"Tips across Veg and Non-Veg\") %>% \n  gf_facet_grid(~Preferance) %>% \n  gf_fitdistr(dist = \"dnorm\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe data we collected for both the Vegetarian and Non-Vegetarian groups doesn’t match what we would expect based on our theory. This difference suggests that the sample data is not normally distributed, which means it doesn’t follow the typical bell-shaped curve that we often see in statistics. So it isnt normal for sure !\n\n\n## Let's do a Shapiro-Wilk test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip %>% filter(Preferance == \"Non-veg\") %>% select(Tip) -> NonVeg\ntip %>% filter(Preferance == \"Veg\") %>% select(Tip) -> Veg\nNonVeg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 1\n     Tip\n   <dbl>\n 1     0\n 2     0\n 3     0\n 4    20\n 5     0\n 6     0\n 7     0\n 8     0\n 9     0\n10    20\n# ℹ 20 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nVeg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 1\n     Tip\n   <dbl>\n 1     0\n 2     0\n 3    20\n 4    35\n 5    40\n 6     0\n 7     0\n 8     0\n 9    15\n10   100\n# ℹ 20 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(NonVeg$Tip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  NonVeg$Tip\nW = 0.71661, p-value = 2.747e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(Veg$Tip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  Veg$Tip\nW = 0.6286, p-value = 1.661e-07\n```\n\n\n:::\n:::\n\n\n### What does this tell us ?\n\n**NonVeg Group**:W = 0.71661: A value less than 1 indicates deviation from normality.\np-value = 2.747e-06 (or 0.000002747): This p-value is very low (much lower than 0.05), meaning we reject the null hypothesis of normality.\n\n**Veg Group**:W = 0.6286: Again, a value far from 1, suggesting the data is not normally distributed.\np-value = 1.661e-07 (or 0.0000001661): An extremely low p-value, indicating strong evidence against normality.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(rank(Tip) ~ Preferance, \n   data = tip) %>% \n  broom::tidy(conf.int = TRUE,\n              conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term          estimate std.error statistic  p.value conf.low conf.high\n  <chr>            <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)     30.9        2.81    11.0   8.04e-16    25.3      36.6 \n2 PreferanceVeg   -0.867      3.98    -0.218 8.28e- 1    -8.83      7.09\n```\n\n\n:::\n:::\n\n\n### What is happening here ?\n\n1)**Intercept (30.93)**:\nThink of the intercept as a starting point. If someone didn’t choose vegetarian or non-vegetarian (let’s say they’re just neutral), we would expect their happiness score to be around 30.93. This is a baseline score\n\n2)**Vegetarian Preference (-0.87)**:\nNow, if someone prefers vegetarian food, the happiness score is expected to be about 0.87 points lower than the baseline (30.93). So, if they choose vegetarian, their score would be roughly 30.93 - 0.87 = 30.06.\nHowever, the uncertainty in this estimate is high. The number we see (-0.87) has a high standard error (3.98), which means that we are not very sure about this number. It's like saying, “We think choosing vegetarian makes you a little less happy, but we’re not very confident about it.”\n\n3)**P-value (0.83)**:\nThe p-value tells us how strong our evidence is. A p-value of 0.83 means there's a high chance that the difference we see (the -0.87) could just be due to random chance. In simple terms, we can’t confidently say that being vegetarian actually lowers happiness because this number is much higher than the common threshold (0.05) we use to decide if something is significant.\n\n\n4)**Confidence Intervals**:\nFor the intercept (30.93), we are 95% confident that the true baseline happiness score is between 25.30 and 36.56.\nFor vegetarian preference, the range (-8.83 to 7.09) includes zero. This means it’s possible that being vegetarian has no effect at all on happiness.\n\nHappy Happy \n\n## Lets do the Permutation Test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_amas <- \n  do(4999) * diffmean(data = tip, Tip ~ shuffle(Preferance))\n#null_dist_amas ( comment it out to see the results )\n```\n:::\n\n\nThe code runs a permutation test to check if there's a significant difference in tips between groups with different food preferences.\nThe results show various mean differences calculated from random shuffles, which will help you determine if the observed difference in your data is statistically significant or could have happened by chance.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_diff_tips <- tip %>%\n  group_by(Preferance) %>%\n  summarise(mean_tip = mean(Tip)) %>%\n  summarise(obs_diff = diff(mean_tip)) %>%\n  pull(obs_diff)\n\nnull_dist_tips <- data.frame(diffmean = rnorm(1000, mean = 0, sd = 1)) \ngf_histogram(data = null_dist_tips, ~ diffmean, bins = 25) %>%\n  gf_vline(xintercept = obs_diff_tips, \n           colour = \"red\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Histogram\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngf_ecdf(data = null_dist_tips, ~ diffmean, \n        linewidth = 1) %>%\n  gf_vline(xintercept = obs_diff_tips, \n           colour = \"red\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Cumulative Density\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\nThe first graph compares the observed difference in mean tips from our permutation test to the distribution of those permuted differences. Since the observed difference falls within the range of these permuted means, it indicates that **we don’t have enough evidence to say there’s a real difference in the tips given by Vegetarians and Non-Vegetarians.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproportion_tips <- 1 - prop1(~ diffmean <= obs_diff_tips, data = null_dist_tips)\n\nprint(proportion_tips)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  prop_TRUE \n0.005994006 \n```\n\n\n:::\n:::\n\n\nAgain, 0.005994006 suggests that there is very little evidence to support the idea that there’s a meaningful difference in tips based on food preference. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mosaic)  \nlibrary(broom)   \nlibrary(gt)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test for Tip based on Gender\nmosaic::t_test(Tip ~ Gender, \n               data = tip) %>% \n  broom::tidy() %>% \n  gt() %>%\n  tab_style(\n    style = list(cell_fill(color = \"cyan\"), cell_text(weight = \"bold\")),\n    locations = cells_body(columns = p.value)) %>% \n  tab_header(title = \"t.test for Tip by Gender\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cdwheddail\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cdwheddail table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cdwheddail thead, #cdwheddail tbody, #cdwheddail tfoot, #cdwheddail tr, #cdwheddail td, #cdwheddail th {\n  border-style: none;\n}\n\n#cdwheddail p {\n  margin: 0;\n  padding: 0;\n}\n\n#cdwheddail .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cdwheddail .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cdwheddail .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cdwheddail .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cdwheddail .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cdwheddail .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cdwheddail .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cdwheddail .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cdwheddail .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cdwheddail .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cdwheddail .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cdwheddail .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cdwheddail .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cdwheddail .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cdwheddail .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cdwheddail .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cdwheddail .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cdwheddail .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cdwheddail .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cdwheddail .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cdwheddail .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cdwheddail .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cdwheddail .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cdwheddail .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cdwheddail .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cdwheddail .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cdwheddail .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cdwheddail .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cdwheddail .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cdwheddail .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cdwheddail .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cdwheddail .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cdwheddail .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cdwheddail .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cdwheddail .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cdwheddail .gt_left {\n  text-align: left;\n}\n\n#cdwheddail .gt_center {\n  text-align: center;\n}\n\n#cdwheddail .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cdwheddail .gt_font_normal {\n  font-weight: normal;\n}\n\n#cdwheddail .gt_font_bold {\n  font-weight: bold;\n}\n\n#cdwheddail .gt_font_italic {\n  font-style: italic;\n}\n\n#cdwheddail .gt_super {\n  font-size: 65%;\n}\n\n#cdwheddail .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cdwheddail .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cdwheddail .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cdwheddail .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cdwheddail .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cdwheddail .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cdwheddail .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cdwheddail .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cdwheddail div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>t.test for Tip by Gender</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">2</td>\n<td headers=\"estimate1\" class=\"gt_row gt_right\">12.16667</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">10.16667</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.4312927</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\" style=\"background-color: #00FFFF; font-weight: bold;\">0.6679182</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">55.77114</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-7.290314</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">11.29031</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Welch Two Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Based on these results:**\n\nThere is no statistically significant difference in tips between genders (p-value = 0.6679).\nThe average tip difference is relatively small ($2), and the confidence interval includes zero, suggesting that any observed difference could be due to random chance rather than a real effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear model for Tip based on Gender\nlm(Tip ~ Gender, \n   data = tip) %>% \n  broom::tidy(conf.int = TRUE,\n              conf.level = 0.95) %>% \n  gt() %>%\n  tab_style(\n    style = list(cell_fill(color = \"cyan\"), cell_text(weight = \"bold\")),\n    locations = cells_body(columns = p.value)) %>% \n  tab_header(title = \"Linear Model for Tip by Gender\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fpqfcoqtog\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fpqfcoqtog table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fpqfcoqtog thead, #fpqfcoqtog tbody, #fpqfcoqtog tfoot, #fpqfcoqtog tr, #fpqfcoqtog td, #fpqfcoqtog th {\n  border-style: none;\n}\n\n#fpqfcoqtog p {\n  margin: 0;\n  padding: 0;\n}\n\n#fpqfcoqtog .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fpqfcoqtog .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fpqfcoqtog .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fpqfcoqtog .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fpqfcoqtog .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fpqfcoqtog .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fpqfcoqtog .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fpqfcoqtog .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fpqfcoqtog .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fpqfcoqtog .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fpqfcoqtog .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fpqfcoqtog .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fpqfcoqtog .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fpqfcoqtog .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fpqfcoqtog .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fpqfcoqtog .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fpqfcoqtog .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fpqfcoqtog .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fpqfcoqtog .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fpqfcoqtog .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fpqfcoqtog .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fpqfcoqtog .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fpqfcoqtog .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fpqfcoqtog .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fpqfcoqtog .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fpqfcoqtog .gt_left {\n  text-align: left;\n}\n\n#fpqfcoqtog .gt_center {\n  text-align: center;\n}\n\n#fpqfcoqtog .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fpqfcoqtog .gt_font_normal {\n  font-weight: normal;\n}\n\n#fpqfcoqtog .gt_font_bold {\n  font-weight: bold;\n}\n\n#fpqfcoqtog .gt_font_italic {\n  font-style: italic;\n}\n\n#fpqfcoqtog .gt_super {\n  font-size: 65%;\n}\n\n#fpqfcoqtog .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fpqfcoqtog .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fpqfcoqtog .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fpqfcoqtog .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fpqfcoqtog .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fpqfcoqtog .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fpqfcoqtog .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fpqfcoqtog .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fpqfcoqtog div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"7\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Linear Model for Tip by Gender</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">12.16667</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">3.279011</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.7104679</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\" style=\"background-color: #00FFFF; font-weight: bold;\">0.0004654425</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">5.603012</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">18.730321</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">GenderMale</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-2.00000</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">4.637222</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-0.4312927</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\" style=\"background-color: #00FFFF; font-weight: bold;\">0.6678544425</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-11.282409</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">7.282409</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Based on these results:**\n\nThe average tip for Females is estimated to be $12.17.\nMales are estimated to tip $2.00 less than Females, but this difference is not statistically significant (p-value = 0.6679).\nThe confidence interval for the gender effect includes zero, which means we cannot confidently say that there is a difference in tipping behavior based on gender.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear model with ranked data for Tip based on Gender\nlm(rank(Tip) ~ Gender, \n   data = tip) %>% \n  broom::tidy(conf.int = TRUE,\n              conf.level = 0.95) %>% \n  gt() %>%\n  tab_style(\n    style = list(cell_fill(color = \"cyan\"), cell_text(weight = \"bold\")),\n    locations = cells_body(columns = p.value)) %>% \n  tab_header(title = \"Linear Model with Ranked Tip by Gender\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pcnayuznaq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pcnayuznaq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pcnayuznaq thead, #pcnayuznaq tbody, #pcnayuznaq tfoot, #pcnayuznaq tr, #pcnayuznaq td, #pcnayuznaq th {\n  border-style: none;\n}\n\n#pcnayuznaq p {\n  margin: 0;\n  padding: 0;\n}\n\n#pcnayuznaq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pcnayuznaq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pcnayuznaq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pcnayuznaq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pcnayuznaq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pcnayuznaq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pcnayuznaq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pcnayuznaq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pcnayuznaq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pcnayuznaq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pcnayuznaq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pcnayuznaq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pcnayuznaq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pcnayuznaq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pcnayuznaq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pcnayuznaq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pcnayuznaq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pcnayuznaq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pcnayuznaq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pcnayuznaq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pcnayuznaq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pcnayuznaq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pcnayuznaq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pcnayuznaq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pcnayuznaq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pcnayuznaq .gt_left {\n  text-align: left;\n}\n\n#pcnayuznaq .gt_center {\n  text-align: center;\n}\n\n#pcnayuznaq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pcnayuznaq .gt_font_normal {\n  font-weight: normal;\n}\n\n#pcnayuznaq .gt_font_bold {\n  font-weight: bold;\n}\n\n#pcnayuznaq .gt_font_italic {\n  font-style: italic;\n}\n\n#pcnayuznaq .gt_super {\n  font-size: 65%;\n}\n\n#pcnayuznaq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pcnayuznaq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pcnayuznaq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pcnayuznaq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pcnayuznaq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pcnayuznaq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pcnayuznaq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pcnayuznaq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pcnayuznaq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"7\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Linear Model with Ranked Tip by Gender</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">32.1</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.797310</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">11.4753107</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\" style=\"background-color: #00FFFF; font-weight: bold;\">1.482771e-16</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">26.50058</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">37.699424</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">GenderMale</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">-3.2</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">3.955994</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-0.8088992</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\" style=\"background-color: #00FFFF; font-weight: bold;\">4.218790e-01</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-11.11878</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">4.718781</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Based on these results:**\n\nThe average rank for Females is estimated to be 32.1.\nMales are estimated to have a rank that is 3.2 units lower than Females, but this difference is not statistically significant (p-value = 0.4219).\nThe confidence interval for the gender effect includes zero, reinforcing that we cannot conclude there is a significant difference in rankings based on gender.\n\n\n## Result \n\nThe average tips and their ranks do not support a conclusion that gender influences the amount tipped in this dataset.\nThe observed differences in tips and ranks could likely be attributed to random chance rather than a true effect of gender.\nOverall, this suggests that, at least in this dataset, gender does not appear to be a significant factor influencing tipping behavior.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}