{
  "hash": "cab15fadfdea62515464dbe57c2b050d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"GRADES(A3)\"\nauthor: \"harvallav\"\n---\n\n\n\n# GRADES\n\n## Art, Design, and Vocation are all diff-different\n\n### INTRODUCTION\n\nIn this analysis, we collected data from three distinct academic programs: Bachelor of Design (B.Des), Bachelor of Vocational Studies (B.Voc), and Bachelor of Fine Arts (B.FA). The primary objective of this study is to explore and compare the grading patterns across these diverse courses. Understanding whether grades differ significantly among students in B.Voc, B.FA, and B.Des will provide valuable insights into the academic performance trends within these programs.\n\n![](grade.jpg)\n\n### Setting up the packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'DescTools'\n\nThe following object is masked from 'package:crosstable':\n\n    N\n\nThe following object is masked from 'package:mosaic':\n\n    MAD\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(supernova)\nlibrary(dplyr)\nlibrary(infer)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n:::\n\n\n\n### Reading the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades <-read_csv(\"../../data /grades.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 90 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): Degree, Course, Letter Grade, Gender\ndbl (3): SN, Year, Score\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ngrades\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 90 × 7\n      SN Degree Course  Year `Letter Grade` Score Gender\n   <dbl> <chr>  <chr>  <dbl> <chr>          <dbl> <chr> \n 1     1 B.Des  CAC        2 A                8   F     \n 2     2 B.Des  CAC        2 O                9.6 F     \n 3     3 B.Des  IADP       2 A+               9.2 F     \n 4     4 B.Des  CE         2 O                9.8 F     \n 5     5 B.Des  BSSD       2 P                3   M     \n 6     6 B.Des  CAC        2 O                9.5 F     \n 7     7 B.Des  PSD        2 A+               9   F     \n 8     8 B.Des  PSD        2 A+               9   F     \n 9     9 B.Des  PSD        2 A+               9   F     \n10    10 B.Des  BSSD       3 A+               9   F     \n# ℹ 80 more rows\n```\n\n\n:::\n:::\n\n\n\n## HYPOTHESIS\n\nLet us see if scores in each degree group are normally distributed or not.\n\n## Let's Make a Histogram for this dataset first\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~Score,\n  fill = ~Degree,\n  data = grades, alpha = 0.5\n) %>%\n  gf_vline(xintercept = ~ mean(Score), color = \"red\") %>%\n  gf_labs(\n    title = \"Histograms of Grades\",\n    x = \"(out of 10)\", y = \"Count\"\n  ) %>%\n  gf_text(7 ~ (mean(Score) + 0.5) , \n    label = \"Overall Mean\"\n  ) %>%\n  gf_refine(guides(fill = guide_legend(title = \"Grades\")))\n```\n\n::: {.cell-output-display}\n![](Index4_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\nSo,\n\n### What does this graph suggest us ?\n\nThis histogram helps us see how grades are spread out for different degree groups and where most scores fall. Each color shows a different degree group, and the red line marks the overall average score. By looking at the bars and overlaps, we can tell if some degree groups usually score higher or lower than others and whether most scores are close to the average or spread out unevenly.\n\nHow about we make another histogram but for all majors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~Score,\n  fill = ~Course,\n  data = grades, alpha = 0.5\n) %>%\n  gf_vline(xintercept = ~ mean(Score), color = \"red\") %>%\n  gf_labs(\n    title = \"Histograms of Grades\",\n    x = \"(out of 10)\", y = \"Count\"\n  ) %>%\n  gf_text(7 ~ (mean(Score) + 0.5) , \n    label = \"Overall Mean\"\n  ) %>%\n  gf_refine(guides(fill = guide_legend(title = \"Grades\")))\n```\n\n::: {.cell-output-display}\n![](Index4_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Making a CROSS TABLE\n\nThis table compares scores across three degree groups: B.Des, B.FA, and B.Voc.\n\n**Range**: B.Des scores vary widely (3.0–10.0), while B.FA and B.Voc are more limited. **Median**: B.Des has the highest median score (9.0), followed by B.FA and B.Voc (both 8.0). **Mean & Spread**: B.Des has the highest mean (8.4) but also the most spread (std = 1.3), suggesting more score variation. B.FA has the lowest mean (7.6) with scores tightly grouped (std = 0.8).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades %>% crosstable(Score~Degree ) %>% as_flextable\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-871f1aa6{table-layout:auto;}.cl-871bfa9c{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-871bfaa6{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-871d3c4a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-871d3c54{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-871d4b5e{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-871d4b5f{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-871d4b60{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-871d4b68{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-871d4b69{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-871f1aa6'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-871d4b5e\"><p class=\"cl-871d3c4a\"><span class=\"cl-871bfa9c\">label</span></p></th><th  rowspan=\"2\"class=\"cl-871d4b5e\"><p class=\"cl-871d3c4a\"><span class=\"cl-871bfa9c\">variable</span></p></th><th  colspan=\"3\"class=\"cl-871d4b5f\"><p class=\"cl-871d3c4a\"><span class=\"cl-871bfa9c\">Degree</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-871d4b60\"><p class=\"cl-871d3c4a\"><span class=\"cl-871bfa9c\">B.Des</span></p></th><th class=\"cl-871d4b60\"><p class=\"cl-871d3c4a\"><span class=\"cl-871bfa9c\">B.FA</span></p></th><th class=\"cl-871d4b60\"><p class=\"cl-871d3c4a\"><span class=\"cl-871bfa9c\">B.Voc</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-871d4b68\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">Score</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">Min / Max</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">3.0 / 10.0</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">6.0 / 9.0</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">5.0 / 9.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">Med [IQR]</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">9.0 [8.0;9.0]</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">8.0 [7.0;8.0]</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">8.0 [8.0;9.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">Mean (std)</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">8.4 (1.3)</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">7.6 (0.8)</span></p></td><td class=\"cl-871d4b69\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">8.2 (1.1)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-871d4b68\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">N (NA)</span></p></td><td class=\"cl-871d4b68\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">30 (0)</span></p></td><td class=\"cl-871d4b68\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">30 (0)</span></p></td><td class=\"cl-871d4b68\"><p class=\"cl-871d3c54\"><span class=\"cl-871bfaa6\">30 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\nThis shows B.Des has the highest but most varied scores, while B.FA scores are consistently lower and tightly clustered.\n\nLet us see a cross table with the majors as well because I am just curious\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades %>% crosstable(Score~Course ) %>% as_flextable\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-873c8faa{table-layout:auto;}.cl-8738af16{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8738af20{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-873a31b0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-873a31ba{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-873a3e8a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-873a3e94{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-873a3e95{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-873a3e96{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-873a3e9e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-873c8faa'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-873a3e8a\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">label</span></p></th><th  rowspan=\"2\"class=\"cl-873a3e8a\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">variable</span></p></th><th  colspan=\"15\"class=\"cl-873a3e94\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">Course</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">BSSD</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">CAC</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">CAP</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">CE</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">DMA</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">DMP</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">Film</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">GADP</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">HCD</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">IADP</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">IAIDP</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">ID</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">PSD</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">UIID</span></p></th><th class=\"cl-873a3e95\"><p class=\"cl-873a31b0\"><span class=\"cl-8738af16\">VCSB</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">Score</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">Min / Max</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">3.0 / 9.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 / 9.6</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 / 9.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.0 / 10.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">6.0 / 9.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">5.0 / 9.5</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">6.0 / 8.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 / 9.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 / 9.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 / 9.2</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 / 8.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 / 7.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 / 9.0</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 / 9.5</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 / 9.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">Med [IQR]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">6.0 [4.5;7.5]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.0 [9.0;9.2]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 [8.0;9.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.8 [9.4;9.9]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 [7.0;8.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.0 [7.2;9.5]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 [7.2;8.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.5 [8.0;9.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.5 [8.2;8.8]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 [7.5;8.6]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.5 [7.2;7.8]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 [7.0;7.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.0 [8.0;9.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 [8.0;9.0]</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 [8.0;8.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">Mean (std)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">6.0 (4.2)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.0 (0.5)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.4 (0.5)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">9.6 (0.5)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.5 (0.7)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.2 (1.6)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.5 (0.8)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.5 (0.6)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.5 (0.7)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.1 (1.1)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.5 (0.7)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">7.0 (NA)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.4 (0.9)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.2 (0.9)</span></p></td><td class=\"cl-873a3e9e\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8.0 (0.7)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">N (NA)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">2 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">8 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">5 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">3 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">20 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">11 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">6 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">4 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">2 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">3 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">2 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">1 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">5 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">13 (0)</span></p></td><td class=\"cl-873a3e96\"><p class=\"cl-873a31ba\"><span class=\"cl-8738af20\">5 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\nCE and CAC show high and consistent scores, while BSSD has more varied, lower scores.Interesting.\n\n## ANOVA\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarks<- aov(Score ~ Degree, data = grades)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsupernova::pairwise(marks,\n  correction = \"Bonferroni\",\n  alpha = 0.05, \n  var_equal = TRUE, \n  plot = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Index4_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Pairwise t-tests with Bonferroni correction ─────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nModel: Score ~ Degree\n```\n\n\n:::\n\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDegree\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLevels: 3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFamily-wise error-rate: 0.049\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  group_1 group_2   diff pooled_se      t    df  lower  upper  p_adj\n  <chr>   <chr>    <dbl>     <dbl>  <dbl> <int>  <dbl>  <dbl>  <dbl>\n1 B.FA    B.Des   -0.757     0.201 -3.770    87 -1.191 -0.323  .0009\n2 B.Voc   B.Des   -0.173     0.201 -0.864    87 -0.607  0.261 1.0000\n3 B.Voc   B.FA     0.583     0.201  2.906    87  0.149  1.017  .0139\n```\n\n\n:::\n:::\n\n\n\n### What is this ?\n\nThis displays a confidence intervals for pairwise t-tests with Bonferroni correction. The x-axis represents the 95.1% confidence interval, and the y-axis lists comparisons between different degree programs (B.FA, B.Des, B.Voc).\n\nB.FA - B.Des: The confidence interval crosses zero, suggesting no significant difference in scores between these two programs. B.Voc - B.Des: The confidence interval also crosses zero, indicating no significant difference. B.Voc - B.FA: The confidence interval crosses zero, suggesting no significant difference.\n\nWell, this suggests that there are no statistically significant differences in scores between the degree programs when using a Bonferroni correction. But let us try other tests to check our Hypothesis.\n\n## Let's make a Linear equation for out data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupernova::equation(marks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFitted equation:\nScore = 8.373333 + -0.7566667*DegreeB.FA + -0.1733333*DegreeB.Voc + e\n```\n\n\n:::\n:::\n\n\n\n### Why Did We Do It?\n\nWe created this equation to see how scores differ across degrees. By examining the coefficients, we can see whether certain degrees have higher or lower average scores compared to others.\n\n| Part of the Equation | Meaning | What It Represents |\n|------------------------|------------------------|------------------------|\n| 8.373333 | The starting point (intercept) for scores. | Represents the baseline score for B.Des (the reference category). When all other variables are 0, the expected score is 8.37. |\n| DegreeB.FA | A variable indicating if the degree is B.FA. | Equals **1** if the student is in B.FA, **0** otherwise. |\n| -0.7566667 | This shows how much the score decreases for B.FA. | If the degree is **B.FA**, the average score is **8.37 - 0.76 ≈ 7.61**. |\n| DegreeB.Voc | A variable indicating if the degree is B.Voc. | Equals **1** if the student is in B.Voc, **0** otherwise. |\n| -0.1733333 | This shows how much the score decreases for B.Voc. | If the degree is **B.Voc**, the average score is **8.37 - 0.17 ≈ 8.20**. |\n| `e` | The error term, which captures other factors affecting scores. | It accounts for things not included in the equation that might change the score. |\n\n## Let's do a Shapiro-Wilk test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(broom)\n\ngrades %>%\n  group_by(Degree) %>%\n  group_modify(~ .x %>%      \n    select(Score) %>% \n    pull() %>%  \n    shapiro.test() %>%  \n    broom::tidy()) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n# Groups:   Degree [3]\n  Degree statistic   p.value method                     \n  <chr>      <dbl>     <dbl> <chr>                      \n1 B.Des      0.753 0.0000101 Shapiro-Wilk normality test\n2 B.FA       0.875 0.00211   Shapiro-Wilk normality test\n3 B.Voc      0.887 0.00418   Shapiro-Wilk normality test\n```\n\n\n:::\n:::\n\n\n\n### What do we understand from this data ?\n\nThis is the Shapiro-Wilk test statistic, where values closer to 1 indicate that the data is more likely to be normally distributed.\n\n1)B.Des: 0.75 B.FA: 0.87 B.Voc: 0.89\n\n2)p-value: This indicates the probability that the data for each degree group comes from a normal distribution. B.Des has a very low p-value (0.00001), suggesting strong evidence against normality for B.Des scores. B.FA and B.Voc have low p-values (0.0021 and 0.0042, respectively), which also suggest evidence against normality, though less strongly than B.Des.\n\nSince all p-values are below a typical threshold of 0.05, we reject the null hypothesis of normality for each group. **This suggests that scores in each degree group are not normally distributed.\\\n**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarks$residuals %>%\n  as_tibble() %>%\n  gf_dhistogram(~value, data = .) %>%\n  gf_fitdistr()\n```\n\n::: {.cell-output-display}\n![](Index4_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n##\nmarks$residuals %>%\n  as_tibble() %>%\n  gf_qq(~value, data = .) %>%\n  gf_qqstep() %>%\n  gf_qqline()\n```\n\n::: {.cell-output-display}\n![](Index4_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n```{.r .cell-code}\n##\nshapiro.test(marks$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  marks$residuals\nW = 0.87869, p-value = 5.076e-07\n```\n\n\n:::\n:::\n\n\n\n```         \n**Test Statistic (W)**: The Shapiro-Wilk test statistic W=0.87869W = 0.87869W=0.87869. A value closer to 1 would indicate that the residuals are more likely to be normally distributed. Since 0.87869 is noticeably below 1, it suggests that the residuals may deviate from normality.\n\n**p-value**: The p-value =5.076×10−7= 5.076 \\times 10^{-7}=5.076×10−7, which is far below the common significance level (e.g., 0.05). This very low p-value indicates strong evidence against the null hypothesis of normality.\n```\n\n## Let us do the Levene and Flinger-Killeen Test\n\n(to understand what these tests are refer to the cartoon(A3) blog)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades %>%\n  group_by(Degree) %>%\n  summarise(variance = var(Score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Degree variance\n  <chr>     <dbl>\n1 B.Des     1.74 \n2 B.FA      0.615\n3 B.Voc     1.27 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Not too different...OK on with the test\nDescTools::LeveneTest( Score ~ Degree, data = grades)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in LeveneTest.default(y = y, group = group, ...): group coerced to\nfactor.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2  0.7294 0.4851\n      87               \n```\n\n\n:::\n\n```{.r .cell-code}\n##\nfligner.test(Score ~ Degree, data = grades)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFligner-Killeen test of homogeneity of variances\n\ndata:  Score by Degree\nFligner-Killeen:med chi-squared = 2.2707, df = 2, p-value = 0.3213\n```\n\n\n:::\n:::\n\n\n\n**Levene's Test**\n\nThe p-value (0.4851) is greater than the common significance level (0.05). This means we fail to reject the null hypothesis that the variances are equal across the groups. In simpler terms, there is no significant difference in the variances of scores among the different degrees.\n\n**Fligner-Killeen Test**\n\nSimilarly, the p-value (0.3213) is also greater than 0.05. Therefore, we fail to reject the null hypothesis of equal variances among the groups.\n\nBoth tests suggest that there is **no significant evidence** to conclude that the variances of scores differ among the degrees (B.Des, B.FA, and B.Voc).\n\n## Let is conduct ANOVA using permutations\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(infer)\n\n\nmarks <- grades %>%\n  specify(Score ~ Degree) %>%\n  hypothesise(null = \"independence\") %>%\n  calculate(stat = \"F\")\n\n\nprint(marks) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: Score (numeric)\nExplanatory: Degree (factor)\nNull Hypothesis: independence\n# A tibble: 1 × 1\n   stat\n  <dbl>\n1  3.90\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_infer <- grades%>%\n  specify(Score ~ Degree) %>%\n  hypothesise(null = \"independence\") %>%\n  generate(reps = 4999, type = \"permute\") %>%\n  calculate(stat = \"F\")\n##\nnull_dist_infer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: Score (numeric)\nExplanatory: Degree (factor)\nNull Hypothesis: independence\n# A tibble: 4,999 × 2\n   replicate   stat\n       <int>  <dbl>\n 1         1 0.790 \n 2         2 1.24  \n 3         3 2.79  \n 4         4 0.233 \n 5         5 0.673 \n 6         6 2.08  \n 7         7 0.461 \n 8         8 2.12  \n 9         9 0.952 \n10        10 0.0395\n# ℹ 4,989 more rows\n```\n\n\n:::\n:::\n\n\n\nthis generates 4,999 permutations of the data, randomly shuffling the Degree values to create a null distribution where any observed relationships are purely by chance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_infer %>%\n  visualise(method = \"simulation\") +\n  shade_p_value(obs_stat = marks$stat, direction = \"right\") +\n  scale_x_continuous(trans = \"log10\", expand = c(0, 0)) +\n  coord_cartesian(xlim = c(0.2, 500), clip = \"off\") +\n  annotation_logticks(outside = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in transformation$transform(x): NaNs produced\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in scale_x_continuous(trans = \"log10\", expand = c(0, 0)): log-10\ntransformation introduced infinite values.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Index4_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n## Result   \nIf the observed F-statistic (red line) falls far into the tail of the null distribution, this suggests that the observed differences in scores between groups are unlikely to occur by chance, supporting the rejection of the null hypothesis.\n\nBecause the observed test statistic is still within the range of the null distribution, we fail to reject the null hypothesis of independence. This means that we don't have strong evidence to conclude that Scores differ significantly across the degree programs.\n\n**The permutation test examines whether there is a relationship between Degree and Score.\nThe Shapiro-Wilk test indicates that the score data in each group is not normally distributed.**\n\nIn simple words: based on this data, we can’t say that students' scores are really different among B.Des, B.FA, and B.Voc.\n\n",
    "supporting": [
      "Index4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}